language: cpp
matrix:
  include:
#  - os: linux
#    dist: trusty
#    compiler: clang
#    before_install:
#    - sudo add-apt-repository ppa:kubuntu-ppa/backports -y
#    - sudo apt-get -qq update
#    - sudo apt-get install -y libgtest-dev valgrind cmake
#    - sudo apt-get install --only-upgrade cmake
#    - sudo wget https://github.com/google/googletest/archive/release-1.7.0.tar.gz
#    - sudo tar xf release-1.7.0.tar.gz
#    - cd googletest-release-1.7.0
#    - sudo cmake -DBUILD_SHARED_LIBS=ON .
#    - sudo make
#    - sudo cp -a include/gtest /usr/include
#    - sudo cp -a libgtest_main.so libgtest.so /usr/lib/
#    - g++ -v

  - os: linux
    dist: trusty
    compiler: gcc
    env:
      - COMPILER=g++-4.8
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: [g++-4.8, valgrind]
  - os: linux
    dist: trusty
    compiler: gcc
    env:
      - COMPILER=g++-4.9
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: [g++-4.9, valgrind]
  - os: linux
    dist: trusty
    compiler: gcc
    env:
      - COMPILER=g++-5
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: [g++-5, valgrind]
  - os: linux
    dist: trusty
    compiler: gcc
    env:
      - COMPILER=g++-6
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: [g++-6, valgrind]
  - os: linux
    dist: trusty
    compiler: gcc
    env:
      - COMPILER=g++-7
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: [g++-7, valgrind]

    
before_install:
    # Combine global build options with OS/compiler-dependent options
    - export CMAKE_OPTIONS=${CMAKE_OPTIONS}" "${ENV_CMAKE_OPTIONS}
    - export CXX_FLAGS=${CXX_FLAGS}" "${ENV_CXX_FLAGS}

    # Install google test
    - git clone https://github.com/google/googletest.git
    - mkdir googletest/build
    - cd googletest/build
    - sudo cmake -DBUILD_SHARED_LIBS=ON ..
    - sudo make
    - sudo make install
    - which valgrind
    - cd "${TRAVIS_BUILD_DIR}"


#           - g++
 #          - valgrind
  #         - python-yaml
   #        - lcov
    #       - libgtest-dev
     #      - cmake
install:
    #- if [ "$CXX" = "clang++" ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
    #- echo ${PATH}
    #- echo ${CXX}
    #- ${CXX} --version
    #- ${CXX} -v
    - sudo pip install codecov
    
script:
    ############################################################################
    # Build main and tests
    ############################################################################
     - mkdir -p build
     - cd build
     - cmake ${CMAKE_OPTIONS} -DCMAKE_CXX_FLAGS=${CXX_FLAGS} -DCMAKE_BUILD_TYPE=Coverage -DBUILD_TESTS=ON -DBUILD_EXAMPLE=OFF .. 
     - make
     - make ezc3d_coverage
     - ctest


after_success:
- codecov -t c376990f-2ad6-4f7b-bbdb-5378a52e295c -X gcov
